// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmPTs2woXuRxG2W18a0BQsxtcPNcSHva4',
    appId: '1:51242744401:android:506bd6f9bdab15490a5670',
    messagingSenderId: '51242744401',
    projectId: 'quizmate-f5ee6',
    storageBucket: 'quizmate-f5ee6.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeLWFN7rFGFZAH-p8RIpxy1jdnesGZ0HI',
    appId: '1:51242744401:web:c1b85140da06b0450a5670',
    messagingSenderId: '51242744401',
    projectId: 'quizmate-f5ee6',
    authDomain: 'quizmate-f5ee6.firebaseapp.com',
    storageBucket: 'quizmate-f5ee6.firebasestorage.app',
    measurementId: 'G-GDCH1V1WVF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv63pjScfYEJ_kicHSlTqwsIU2YHtme5w',
    appId: '1:51242744401:ios:aca57e613cc64dce0a5670',
    messagingSenderId: '51242744401',
    projectId: 'quizmate-f5ee6',
    storageBucket: 'quizmate-f5ee6.firebasestorage.app',
    iosBundleId: 'com.example.quizmateapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv63pjScfYEJ_kicHSlTqwsIU2YHtme5w',
    appId: '1:51242744401:ios:aca57e613cc64dce0a5670',
    messagingSenderId: '51242744401',
    projectId: 'quizmate-f5ee6',
    storageBucket: 'quizmate-f5ee6.firebasestorage.app',
    iosBundleId: 'com.example.quizmateapp',
  );

}